### ISSUE TITLE
diag_table.yaml schema updates needed for global_meta and attributes

### ISSUE THREAD

**Issue by uramirez8707** [NOAA-GFDL/gfdl_msd_schemas#11]
The schema for the diag_table.yaml needs to be updated so that `global_meta` and `attributes` allows an array of key/value pairs such as
https://github.com/NOAA-GFDL/FMS/blob/main/diag_manager/diag_yaml_format.md#25-global-meta-data-section
https://github.com/NOAA-GFDL/FMS/blob/main/diag_manager/diag_yaml_format.md#24-variable-metadata-section

It currently allows anything:
https://github.com/NOAA-GFDL/gfdl_msd_schemas/blob/1cf91bfc14bf8cd19adadc0c51059f7922802cd1/FMS/diag_table.json#L47-L48
https://github.com/NOAA-GFDL/gfdl_msd_schemas/blob/1cf91bfc14bf8cd19adadc0c51059f7922802cd1/FMS/diag_table.json#L162-L163

**Comment by J-Lentz** [comment]
Are attribute values allowed to be any scalar type, or should they always be strings?
