### ISSUE TITLE
`gfdl_msd_schemas` python packaging / pip installable 

### ISSUE THREAD

**Issue by ilaflott** [NOAA-GFDL/gfdl_msd_schemas#13]
[fre-cli/issue #187](https://github.com/NOAA-GFDL/fre-cli/issues/187) suggests originally that `gfdl_msd_schemas` should be a `git submodule`, meaning the repo should be cloned recursively, so that `fre make` has easy access to the schemas.

[what i learned trying to make `fms_yaml_tools` a conda package](https://github.com/NOAA-GFDL/fms_yaml_tools/pull/66) taught me that one cannot build a conda package containing code "not owned" by the base repository. Now locally, if one removes the `.git` from `gfdl_msd_schemas` after cloning `fms_yaml_tools` recursively, the package will build. 

but, in github CI/CD, where `fre-cli`'s automagic `conda publish` occurs after a push to main, [it simply doesn't seem to work](https://github.com/NOAA-GFDL/fms_yaml_tools/pull/66#issuecomment-2419913056)!

So, since both `fms_yaml_tools` and `fre-cli` are python-based, and both wish to have access to `gfdl_msd_schemas`, and there's a future intention to [plug `fms_yaml_tools` into `fre-cli`](https://github.com/NOAA-GFDL/fre-cli/pull/202), and `fre-cli` is primarily a conda package, having `gfdl_msd_schemas` be `pip`-installable means we can integrate everything under one conda environment at the next step.

**Comment by singhd789** [comment]
@ilaflott Thank you for making this issue! I wanted to play around with it a little bit more

**Comment by ilaflott** [comment]
closing, we figured out how to use `gfdl_msd_schemas` as a `git submodule` thanks to people figuring out [fre-cli #253](https://github.com/NOAA-GFDL/fre-cli/pull/253/files)
